on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.15.0'
          - '8.14'
          - '8.13.2'
          - '8.13.1'
          - '8.13'
        ocaml_version:
          - '4.12.0-flambda'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'mirrorsolve.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          before_install: opam repo add coq-released https://coq.inria.fr/opam/released

